// Dashboard display data is deliberately kept separate from view components.

export const navItems = [
  {
    id: "overview",
    label: "Overview",
    mobileLabel: "Home",
    group: "Analyze",
    icon: "grid",
  },
  {
    id: "spend",
    label: "Spend & revenue",
    mobileLabel: "Spend",
    group: "Analyze",
    icon: "trend",
  },
  {
    id: "models",
    label: "Models",
    mobileLabel: "Models",
    group: "Analyze",
    icon: "models",
  },
  {
    id: "users",
    label: "Users",
    mobileLabel: "Users",
    group: "Analyze",
    icon: "users",
  },
  {
    id: "invoices",
    label: "Invoices",
    mobileLabel: "Invoices",
    group: "Manage",
    icon: "invoice",
  },
  {
    id: "settings",
    label: "Settings",
    mobileLabel: "Settings",
    group: "Manage",
    icon: "settings",
  },
];

export const workspaceOptions = [
  { name: "OneAI Bangladesh", mark: "OA", detail: "7,761 members" },
  { name: "Product Lab", mark: "PL", detail: "32 members" },
  { name: "Sandbox", mark: "SB", detail: "8 members" },
];

export const planSummary = [
  {
    name: "Free",
    users: "5,841",
    revenue: "BDT 0",
    cost: "BDT 18,420",
    color: "#aeb5af",
    revenueWidth: "18%",
    costWidth: "30%",
  },
  {
    name: "Lite",
    users: "1,284",
    revenue: "BDT 127,116",
    cost: "BDT 38,610",
    color: "#7faedb",
    revenueWidth: "73%",
    costWidth: "61%",
  },
  {
    name: "Plus",
    users: "550",
    revenue: "BDT 164,450",
    cost: "BDT 57,800",
    color: "#ad87c7",
    revenueWidth: "94%",
    costWidth: "91%",
  },
  {
    name: "Pro",
    users: "86",
    revenue: "BDT 68,714",
    cost: "BDT 11,670",
    color: "#caa05d",
    revenueWidth: "42%",
    costWidth: "18%",
  },
];

export const usageData = {
  Plus: {
    users: "550",
    avgTokens: "11.6M",
    avgCost: "BDT 105.09",
    topShare: "21.8%",
    bottomShare: "0.2%",
    top: [
      ["Amara Lewis", "amara@fable.studio", "58.4M", "BDT 526"],
      ["Theo Park", "theo@northstar.ai", "51.9M", "BDT 469"],
      ["Maya Chen", "maya@loomlabs.co", "49.8M", "BDT 450"],
      ["Jordan Rivera", "jordan@lemonade.io", "46.7M", "BDT 421"],
      ["Ishaan Shah", "ishaan@wavelength.dev", "42.3M", "BDT 381"],
      ["Elena Rossi", "elena@typeformly.com", "40.1M", "BDT 361"],
      ["Noah Williams", "noah@meridian.co", "38.6M", "BDT 348"],
      ["Priya Nair", "priya@relay.app", "36.9M", "BDT 332"],
      ["Lucas Martin", "lucas@aperture.ai", "35.4M", "BDT 319"],
      ["Sara Kim", "sara@fuse.com", "33.7M", "BDT 304"],
    ],
    bottom: [
      ["Ben Carter", "ben@pulse.dev", "0.42M", "BDT 4"],
      ["Olivia Reed", "olivia@cinder.io", "0.48M", "BDT 4"],
      ["Nina Patel", "nina@concord.co", "0.51M", "BDT 5"],
      ["Jack Wilson", "jack@fieldnote.app", "0.54M", "BDT 5"],
      ["Eva Green", "eva@hearth.studio", "0.59M", "BDT 5"],
      ["Owen Brooks", "owen@oakline.co", "0.63M", "BDT 6"],
      ["Lena Hoffmann", "lena@horizon.de", "0.66M", "BDT 6"],
      ["Samir Khan", "samir@clarity.io", "0.69M", "BDT 6"],
      ["Ava Johnson", "ava@tidal.app", "0.73M", "BDT 7"],
      ["Miles Cooper", "miles@parallel.co", "0.78M", "BDT 7"],
    ],
  },
  Pro: {
    users: "86",
    avgTokens: "37.3M",
    avgCost: "BDT 135.70",
    topShare: "34.5%",
    bottomShare: "0.8%",
    top: [
      ["Wen Yao", "wen@keystone.ai", "164.8M", "BDT 2,290"],
      ["David Stone", "david@signalgrid.io", "147.2M", "BDT 2,045"],
      ["Reese Morgan", "reese@arcadia.com", "139.5M", "BDT 1,937"],
      ["Fatima Ali", "fatima@ultra.work", "132.1M", "BDT 1,834"],
      ["Cameron Lee", "cameron@field.ai", "128.6M", "BDT 1,785"],
      ["Harper White", "harper@weave.one", "121.4M", "BDT 1,686"],
      ["Mateo Silva", "mateo@brio.dev", "117.7M", "BDT 1,635"],
      ["Zoe Miller", "zoe@bloom.co", "113.2M", "BDT 1,572"],
      ["Andre Bell", "andre@source.io", "109.9M", "BDT 1,527"],
      ["Keiko Tanaka", "keiko@canvas.jp", "106.4M", "BDT 1,478"],
    ],
    bottom: [
      ["Jon Bell", "jon@koko.ai", "3.12M", "BDT 43"],
      ["Mary James", "mary@inlet.io", "3.48M", "BDT 48"],
      ["Ari Singh", "ari@barge.co", "3.77M", "BDT 52"],
      ["Talia Moore", "talia@waypoint.dev", "4.09M", "BDT 57"],
      ["Emil Novak", "emil@alto.ai", "4.33M", "BDT 60"],
      ["Kara Ng", "kara@amber.co", "4.61M", "BDT 64"],
      ["Diego Cruz", "diego@splice.io", "4.84M", "BDT 67"],
      ["June Park", "june@parade.app", "5.13M", "BDT 71"],
      ["Aiden Cole", "aiden@lasso.co", "5.42M", "BDT 75"],
      ["Riya Das", "riya@folklore.dev", "5.78M", "BDT 80"],
    ],
  },
  Lite: {
    users: "1,284",
    avgTokens: "4.3M",
    avgCost: "BDT 30.07",
    topShare: "18.6%",
    bottomShare: "0.1%",
    top: [
      ["Claire Dubois", "claire@atelier.fr", "29.7M", "BDT 208"],
      ["Marcus Hill", "marcus@glide.app", "27.9M", "BDT 195"],
      ["Yuki Sato", "yuki@zenith.jp", "26.4M", "BDT 184"],
      ["Anika Bose", "anika@forage.io", "25.8M", "BDT 180"],
      ["Tom Davies", "tom@beacon.uk", "24.3M", "BDT 170"],
      ["Mina Cho", "mina@kinetic.co", "23.7M", "BDT 166"],
      ["Vikram Rao", "vikram@orbit.dev", "22.9M", "BDT 160"],
      ["Ivy Scott", "ivy@hush.io", "22.4M", "BDT 157"],
      ["Felix Meyer", "felix@sonder.de", "21.8M", "BDT 153"],
      ["Ada Brooks", "ada@copper.app", "21.2M", "BDT 148"],
    ],
    bottom: [
      ["Max Chen", "max@orbit.co", "0.08M", "BDT 1"],
      ["Ellie Wood", "ellie@lark.app", "0.09M", "BDT 1"],
      ["Jo Kim", "jo@inside.io", "0.10M", "BDT 1"],
      ["Ray Singh", "ray@newline.co", "0.11M", "BDT 1"],
      ["Liam Fox", "liam@north.io", "0.12M", "BDT 1"],
      ["Chloe Bell", "chloe@amity.app", "0.13M", "BDT 1"],
      ["Nora Liu", "nora@glow.co", "0.14M", "BDT 1"],
      ["Neil Ross", "neil@crest.ai", "0.15M", "BDT 1"],
      ["Amy Hart", "amy@twig.io", "0.16M", "BDT 1"],
      ["Leo Wood", "leo@dash.app", "0.17M", "BDT 1"],
    ],
  },
  Free: {
    users: "5,841",
    avgTokens: "0.81M",
    avgCost: "BDT 3.15",
    topShare: "12.3%",
    bottomShare: "0.03%",
    top: [
      ["Abby Wright", "abby@hello.co", "12.8M", "BDT 101"],
      ["Ethan Hall", "ethan@acorn.app", "11.9M", "BDT 94"],
      ["Mira Shah", "mira@spring.io", "11.4M", "BDT 90"],
      ["Kai Lewis", "kai@learn.dev", "10.9M", "BDT 86"],
      ["Grace Kim", "grace@plane.so", "10.6M", "BDT 84"],
      ["Caleb West", "caleb@basil.app", "10.1M", "BDT 80"],
      ["Mia Walker", "mia@prism.co", "9.8M", "BDT 77"],
      ["Ron Li", "ron@linen.io", "9.3M", "BDT 74"],
      ["Joan Reed", "joan@light.app", "8.9M", "BDT 70"],
      ["Finn Rose", "finn@lattice.co", "8.7M", "BDT 69"],
    ],
    bottom: [
      ["Toby Hill", "toby@plain.co", "0.01M", "BDT 0.08"],
      ["Ana Noor", "ana@form.app", "0.01M", "BDT 0.08"],
      ["Ira Cole", "ira@root.io", "0.01M", "BDT 0.08"],
      ["Bea Moss", "bea@moon.co", "0.01M", "BDT 0.08"],
      ["Ali Khan", "ali@luna.dev", "0.02M", "BDT 0.16"],
      ["Drew Ford", "drew@solo.io", "0.02M", "BDT 0.16"],
      ["Jill Ray", "jill@echo.app", "0.02M", "BDT 0.16"],
      ["Paul Day", "paul@circa.ai", "0.02M", "BDT 0.16"],
      ["Cleo Sun", "cleo@atlas.co", "0.02M", "BDT 0.16"],
      ["Hugo Bell", "hugo@sparrow.app", "0.02M", "BDT 0.16"],
    ],
  },
};

export const modelRows = [
  {
    name: "GPT",
    provider: "OpenAI",
    logo: "gpt.svg",
    tokens: "3.14B",
    share: "36.4%",
    width: "100%",
    unit: "BDT 16.50",
    cost: "BDT 51,720",
    category: "Language",
  },
  {
    name: "Claude",
    provider: "Anthropic",
    logo: "claude.svg",
    tokens: "2.06B",
    share: "23.9%",
    width: "66%",
    unit: "BDT 13.20",
    cost: "BDT 27,200",
    category: "Language",
  },
  {
    name: "Gemini",
    provider: "Google",
    logo: "gemini.svg",
    tokens: "1.67B",
    share: "19.4%",
    width: "54%",
    unit: "BDT 13.68",
    cost: "BDT 22,850",
    category: "Language",
  },
  {
    name: "Grok",
    provider: "xAI",
    logo: "grok.svg",
    tokens: "1.02B",
    share: "11.8%",
    width: "33%",
    unit: "BDT 12.75",
    cost: "BDT 13,000",
    category: "Language",
  },
  {
    name: "DeepSeek",
    provider: "DeepSeek",
    logo: "deepseek.svg",
    tokens: "0.73B",
    share: "8.5%",
    width: "24%",
    unit: "BDT 16.07",
    cost: "BDT 11,730",
    category: "Language",
  },
];

export const modelCatalog = [
  {
    name: "GPT",
    provider: "OpenAI",
    type: "Text",
    logo: "gpt.svg",
    description: "Complex reasoning, coding, and agentic workflows.",
    latency: "1.8s",
    enabled: true,
  },
  {
    name: "Claude",
    provider: "Anthropic",
    type: "Text",
    logo: "claude.svg",
    description: "Long-context writing and analytical work.",
    latency: "2.2s",
    enabled: true,
  },
  {
    name: "Gemini",
    provider: "Google",
    type: "Multimodal",
    logo: "gemini.svg",
    description: "Research, files, and multimodal reasoning.",
    latency: "2.5s",
    enabled: true,
  },
  {
    name: "DeepSeek",
    provider: "DeepSeek",
    type: "Text",
    logo: "deepseek.svg",
    description: "Efficient everyday chat, code, and research.",
    latency: "0.7s",
    enabled: true,
  },
  {
    name: "Grok",
    provider: "xAI",
    type: "Text",
    logo: "grok.svg",
    description: "Real-time search and conversation tasks.",
    latency: "1.3s",
    enabled: false,
  },
  {
    name: "MiniMax",
    provider: "MiniMax",
    type: "Video",
    logo: "minimax.svg",
    description: "Premium video creation workflows.",
    latency: "4.1s",
    enabled: false,
  },
  {
    name: "Veo",
    provider: "Google",
    type: "Video",
    logo: "veo.svg",
    description: "Polished motion and visual storytelling.",
    latency: "6.4s",
    enabled: false,
  },
];

export const memberSeed = [
  ["Sofia Morgan", "sofia@oneaibd.com", "Admin", "Pro", "45.2M", "Just now"],
  ["Amara Lewis", "amara@fable.studio", "Member", "Plus", "58.4M", "4 min ago"],
  ["Theo Park", "theo@northstar.ai", "Member", "Plus", "51.9M", "21 min ago"],
  ["Maya Chen", "maya@loomlabs.co", "Admin", "Plus", "49.8M", "1 hr ago"],
  ["Wen Yao", "wen@keystone.ai", "Member", "Pro", "164.8M", "2 hr ago"],
  [
    "Claire Dubois",
    "claire@atelier.fr",
    "Member",
    "Lite",
    "29.7M",
    "Yesterday",
  ],
  ["Abby Wright", "abby@hello.co", "Member", "Free", "12.8M", "2 days ago"],
];

export const avatarColors = [
  ["#deece4", "#215c45"],
  ["#ebe1d4", "#70482c"],
  ["#e2e5f3", "#475681"],
  ["#f1e0e0", "#874d4b"],
  ["#ece7d6", "#6a5d2e"],
  ["#dcecf0", "#2c6470"],
  ["#e9dfe9", "#755371"],
  ["#e5e7dc", "#4e5d39"],
];
